server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      #routes:
      #  - id: buscador-service
      #    uri: lb://buscador-service
      #    predicates:
      #      - Path=/api/products/**, /api/suppliers/**
      #  - id: operador-service
      #    uri: lb://operador-service
      #    predicates:
      #      - Path=/api/supply-orders/**, /api/shipments/**, /api/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
    hostname: ${EUREKA_HOST:localhost}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
